import pstats, cProfile

import pyximport
import numpy as np

pyximport.install(setup_args={"include_dirs": np.get_include()})

import align_cython

cProfile.runctx(
    "align_cython.align_seq_2('SSSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDRRTEEENLRK',"
    "'SSVPSQKTYQGSYGFRLGFLHSGTAKSVTCTYSPALNKMFCQLAKTCPVQLWVDSTPPPGTRVRAMAIYKQSQHMTEVVRRCPHHERCSDSDGLAPPQHLIRVEGNLRVEYLDDRNTFRHSVVVPYEPPEVGSDCTTIHYNYMCNSSCMGGMNRRPILTIITLEDSSGNLLGRNSFEVRVCACPGRDWRTEEENLRKK')",
    globals(),
    locals(),
    "Profile.prof",
)

s = pstats.Stats("Profile.prof")
s.strip_dirs().sort_stats("time").print_stats()
